version: '3'

services:
  api:
    build: .
    ports:
      - 8000:80
    volumes:
      - .:/app
    # command for local development server
    #command: uvicorn server:app --port 80 --host 0.0.0.0 --reload
    command: tail -f /dev/null

